[package]
name = "e2store"
keywords = ["ethereum", "portal-network", "e2store", "era", "era1"]
description = "E2store, era, and era1 implementations for Ethereum"
authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.4.1"

[dependencies]
alloy = { workspace = true, features = ["rlp", "consensus"] }
alloy-rlp.workspace = true
anyhow.workspace = true
ethereum_ssz.workspace = true
ethereum_ssz_derive.workspace = true
ethportal-api.workspace = true
rand.workspace = true
snap.workspace = true

[dev-dependencies]
rstest.workspace = true
trin-utils.workspace = true
